apiVersion: skaffold/v2beta18
kind: Config
profiles:
  - name: dev
    build:
      local:
        push: true # false는 로컬 테스트
      artifacts:
        - image: skaqud/simple-api # on dev server
        # - image: simple-api   # local
          jib:
            args:
              - -DskipTests
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=dev"
            fromImage: openjdk:11.0.11-jre-slim
    deploy:
      kubectl:
        manifests:
          - k8s/dev/*.yaml
    # portForward:
    # - resourceType: Service
    #   resourceName: simple-api-service
    #   namespace: api
    #   port: 80
    #   localPort: 8082 # *Optional*